### ISSUE TITLE
how to help getting this project unstuck?

### ISSUE THREAD

**Issue by immerda** [saml-idp/saml_idp#125]
dear owners of this repo (@jphenow),
it seems this repo is somewhat popular, there is a backlog of useful additions and a small community of users who seem to be willing to contribute. It would be great to get it somehow unstuck! Please let us know how we can help to achieve this! For example I would love to donate some time reviewing open PR's, or help out in any other way.

**Comment by jphenow** [comment]
I do my best, but for historical reference I'll replay how we wound up here.

I worked for Sports Engine, a startup local to me, for a few years. In my time there, there was a need for a SAML idp. I didn't want to write one entirely by hand, but all available libraries were half-baked virtual test libraries. So I spun off of one of those, rewrote it from the ground up using the information I gleaned from their work - mostly this Lawrence Pit fellow. The needs of the library's growth had more or less slowed - it did what they needed. Shortly after that, I left the company. This was 2015. Interestingly, the SAML saga at my job was a very small one.

Fast forward one job and some years; I don't work on Ruby full time, and I certainly don't work on SAML even a little bit.

Some time in the last few years, though, someone reached out to me and the company because at this point the company still owns the repository. They wanted to take on some of the ownership, responsibilities, and Internet points. I said _great_, *finally*. Like you say, people clearly want to use the project. I'd love to help it grow but frankly it's near the bottom of totem pole of interest and care at the point. So, with the help of the folks at Sports Engine we spin off a separate, Open Source organization and this new fellow jumps in dropping his name all over everything - gotta get those points. Then suddenly he's no where to be found. I messaged him and eventually found out the project that needed SAML is no longer really needed so his focus has changed. I don't mean to knock this guy, because I understand how that goes. I do somewhat knock kicking off an entire org change, giving someone the keys who hasn't really proved they can provide the value needed - but that one's probably on me. I got a little too excited, thinking that I thought I found someone who could shepherd this into a better place. 

Fast forward another job and some years; I seldom work on Ruby, I sometimes work on Authentication systems, but almost never SAML.

So, that's all to say, if you want to help dust off issues, and pull requests to get them ready with an @ to me to finish them off - that sounds great to me. I will continue to do my best - though that will likely be less than what people want or need. If the assistance progresses for some time, I'm happy to upgrade your access to streamline things. Help has and always will be appreciated.
