### ISSUE TITLE
Is this used in production?

### ISSUE THREAD

**Issue by steobrien** [saml-idp/saml_idp#165]
Hey there, thanks for this great-looking library.

I'd love to know of any social proof here – i.e. who's running this in production? That'd be really helpful in deciding whether or not to use your code. If available, I think that'd be a great addition to the readme.

Apologies if I missed this anywhere!

**Comment by Zogoo** [comment]
@steobrien I have sure that a lot of guys are using this gem for their production environment. But I'm not sure that someone really wants to put their name in here.

From my experience this open source code does enough things for the SAML 2.0 protocol as low level library.
But way to run it on production will very depends on developer who using this gem in their application (e.g Rails, Sinatra). 
And as you know SAML is core security is signature and encryption. I think the implementation of "how protect your IdP private key" should be the main challenge for your production application.

And I think no one wants to share that knowledge in public repo. That's why you might not hear services names those uses this gem.
