### ISSUE TITLE
IdP seems to be encoding the callback url's query string in a weird way

### ISSUE THREAD

**Issue by thatandyrose** [saml-idp/saml_idp#176]
This is more of a question... as in, is this how SAML IdPs behave or is this a bug?

**What's the issue?**

Upon building a SAML request, if I set the callback url to something like: 

`http://whatver.com/users/auth/saml/callback?something=hello`

then upon successful IdP login, the above url is called as it appears above, i.e:

`http://whatver.com/users/auth/saml/callback?something=hello`

HOWEVER, if I include a 2nd query string param in the callback url like this:

`http://whatver.com/users/auth/saml/callback?something=hello&message=bye`

then the Idp ends up calling THIS url:

`http://whatver.com/users/auth/saml/callback?something=hello&amp;message=bye`

Notice the `&amp;`

Is this expected behavior, and/o. should I expect other IdPs to behave in this way?

**Comment by keithwongg** [comment]
My IdP doesn't have the params in the callback url. I could be wrong but I think the return callback should be a POST because it contains other data like the x509 cert, fingerprint, digest value and other attributes that you would want to pass to the Service Provider (SP) from the IdP.

You can set the config attributes under `config.attributes` in config > initializers > saml.rb.

In addition, you can also use firefox and download this add on: https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/

This add on can trace the XML data passed between SP and IdP and you can see if you have the correct configurations set.

**Comment by Zogoo** [comment]
@thatandyrose when you say "callback url" do you mean RelayState for SP? 
If yes, it has nothing to do with the IDP feature.
If you just created a POST form like this example. Gem just re-submitting the original request parameter. SP should react for this URL. If this is the case and you have this strange encoding in your browser I suggest encoding the RelayState URL with an online URL encoder and set in your SP provider config.
https://github.com/saml-idp/saml_idp/wiki/Rails_Integration#create-view-for-post-request-saml-response
